# Form implementation generated from reading ui file 'ui_help.ui'
#
# Created by: PyQt6 UI code generator 6.1.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
from modules.interaction.widget import QClickLabel


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(551, 375)
        self.centralWidget = QtWidgets.QWidget(Form)
        self.centralWidget.setGeometry(QtCore.QRect(10, 10, 531, 351))
        self.centralWidget.setObjectName("centralWidget")
        self.label_7 = QtWidgets.QLabel(self.centralWidget)
        self.label_7.setGeometry(QtCore.QRect(65, 150, 381, 42))
        self.label_7.setStyleSheet("font-size: 22px;")
        self.label_7.setObjectName("label_7")
        self.titleFrame = QtWidgets.QFrame(self.centralWidget)
        self.titleFrame.setGeometry(QtCore.QRect(-20, -10, 561, 61))
        self.titleFrame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.titleFrame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.titleFrame.setObjectName("titleFrame")
        self.label_3 = QtWidgets.QLabel(self.titleFrame)
        self.label_3.setGeometry(QtCore.QRect(30, 30, 51, 16))
        self.label_3.setStyleSheet("font-size: 16px;")
        self.label_3.setObjectName("label_3")
        self.closeBtnLabel = QClickLabel(self.titleFrame)
        self.closeBtnLabel.setGeometry(QtCore.QRect(520, 30, 10, 10))
        self.closeBtnLabel.setMaximumSize(QtCore.QSize(10, 10))
        self.closeBtnLabel.setObjectName("closeBtnLabel")
        self.appIconLabel = QtWidgets.QLabel(self.centralWidget)
        self.appIconLabel.setGeometry(QtCore.QRect(480, 300, 40, 41))
        self.appIconLabel.setMinimumSize(QtCore.QSize(40, 40))
        self.appIconLabel.setObjectName("appIconLabel")
        self.label_2 = QtWidgets.QLabel(self.centralWidget)
        self.label_2.setGeometry(QtCore.QRect(65, 320, 281, 16))
        self.label_2.setStyleSheet("font-size: 14px;")
        self.label_2.setObjectName("label_2")
        self.layoutWidget = QtWidgets.QWidget(self.centralWidget)
        self.layoutWidget.setGeometry(QtCore.QRect(65, 220, 251, 71))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.expireDateLabel = QtWidgets.QLabel(self.layoutWidget)
        self.expireDateLabel.setStyleSheet("font-size: 14px; color:#FE8D08")
        self.expireDateLabel.setObjectName("expireDateLabel")
        self.gridLayout.addWidget(self.expireDateLabel, 1, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.layoutWidget)
        self.label_5.setStyleSheet("font-size: 14px;")
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 1, 0, 1, 1)
        self.activeUserLabel = QtWidgets.QLabel(self.layoutWidget)
        self.activeUserLabel.setStyleSheet("font-size: 14px;")
        self.activeUserLabel.setObjectName("activeUserLabel")
        self.gridLayout.addWidget(self.activeUserLabel, 0, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.layoutWidget)
        self.label_4.setStyleSheet("font-size: 14px; color: #2358DE;")
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 0, 1, 1, 1)
        self.gridLayout.setColumnStretch(0, 1)
        self.gridLayout.setColumnStretch(1, 2)
        self.companyLogoLabel = QtWidgets.QLabel(self.centralWidget)
        self.companyLogoLabel.setGeometry(QtCore.QRect(50, 50, 331, 111))
        self.companyLogoLabel.setObjectName("companyLogoLabel")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_7.setText(_translate("Form", "敏感信息监测系统HawkSec 2022.1.1"))
        self.label_3.setText(_translate("Form", "帮助"))
        self.closeBtnLabel.setText(_translate("Form", "x"))
        self.appIconLabel.setText(_translate("Form", "icon"))
        self.label_2.setText(_translate("Form", "Copyright 2022-2023 ShengDa CO., LTD"))
        self.expireDateLabel.setText(_translate("Form", "2022年9月30日"))
        self.label_5.setText(_translate("Form", "订阅有效期至"))
        self.activeUserLabel.setText(_translate("Form", "证书激活用户"))
        self.label_4.setText(_translate("Form", "Test User"))
        self.companyLogoLabel.setText(_translate("Form", "company logo"))
