# Form implementation generated from reading ui file 'ui_logview.ui'
#
# Created by: PyQt5 UI code generator 6.3.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from modules.interaction.widget import QClickLabel


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(872, 553)
        Form.setMinimumSize(QtCore.QSize(860, 510))
        Form.setStyleSheet("")
        self.centralWidget = QtWidgets.QWidget(Form)
        self.centralWidget.setGeometry(QtCore.QRect(10, 10, 851, 531))
        self.centralWidget.setObjectName("centralWidget")
        self.logTextEdit = QtWidgets.QPlainTextEdit(self.centralWidget)
        self.logTextEdit.setGeometry(QtCore.QRect(10, 60, 831, 421))
        self.logTextEdit.setReadOnly(True)
        self.logTextEdit.setPlaceholderText("")
        self.logTextEdit.setObjectName("logTextEdit")
        self.cancelBtn = QtWidgets.QPushButton(self.centralWidget)
        self.cancelBtn.setGeometry(QtCore.QRect(390, 490, 61, 30))
        self.cancelBtn.setMinimumSize(QtCore.QSize(60, 30))
        self.cancelBtn.setObjectName("cancelBtn")
        self.clearBtn = QtWidgets.QPushButton(self.centralWidget)
        self.clearBtn.setGeometry(QtCore.QRect(310, 490, 61, 30))
        self.clearBtn.setMinimumSize(QtCore.QSize(60, 30))
        self.clearBtn.setObjectName("clearBtn")
        self.titleFrame = QtWidgets.QFrame(self.centralWidget)
        self.titleFrame.setGeometry(QtCore.QRect(-20, -10, 881, 61))
        self.titleFrame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.titleFrame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.titleFrame.setObjectName("titleFrame")
        self.label_2 = QtWidgets.QLabel(self.titleFrame)
        self.label_2.setGeometry(QtCore.QRect(30, 30, 81, 16))
        self.label_2.setStyleSheet("font-size: 16px;")
        self.label_2.setObjectName("label_2")
        self.closeBtnLabel = QClickLabel(self.titleFrame)
        self.closeBtnLabel.setGeometry(QtCore.QRect(850, 30, 10, 10))
        self.closeBtnLabel.setMaximumSize(QtCore.QSize(10, 10))
        self.closeBtnLabel.setObjectName("closeBtnLabel")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "详情页"))
        self.cancelBtn.setText(_translate("Form", "取消"))
        self.clearBtn.setText(_translate("Form", "清空"))
        self.label_2.setText(_translate("Form", "运行日志"))
        self.closeBtnLabel.setText(_translate("Form", "x"))
