# Form implementation generated from reading ui file 'ui_msgbox.ui'
#
# Created by: PyQt6 UI code generator 6.1.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
from modules.interaction.widget import QClickLabel


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(413, 193)
        self.centralWidget = QtWidgets.QWidget(Dialog)
        self.centralWidget.setGeometry(QtCore.QRect(10, 10, 391, 171))
        self.centralWidget.setObjectName("centralWidget")
        self.layoutWidget = QtWidgets.QWidget(self.centralWidget)
        self.layoutWidget.setGeometry(QtCore.QRect(250, 120, 128, 32))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.okBtn = QtWidgets.QPushButton(self.layoutWidget)
        self.okBtn.setMinimumSize(QtCore.QSize(60, 30))
        self.okBtn.setMaximumSize(QtCore.QSize(60, 30))
        self.okBtn.setObjectName("okBtn")
        self.horizontalLayout.addWidget(self.okBtn)
        self.cancelBtn = QtWidgets.QPushButton(self.layoutWidget)
        self.cancelBtn.setMinimumSize(QtCore.QSize(60, 30))
        self.cancelBtn.setMaximumSize(QtCore.QSize(60, 30))
        self.cancelBtn.setObjectName("cancelBtn")
        self.horizontalLayout.addWidget(self.cancelBtn)
        self.titleLabel = QtWidgets.QLabel(self.centralWidget)
        self.titleLabel.setGeometry(QtCore.QRect(20, 20, 41, 21))
        self.titleLabel.setStyleSheet("color: #2E3033; font-weight: 400; font-size: 16px;")
        self.titleLabel.setObjectName("titleLabel")
        self.layoutWidget_2 = QtWidgets.QWidget(self.centralWidget)
        self.layoutWidget_2.setGeometry(QtCore.QRect(40, 63, 341, 41))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.layoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(16)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.iconLabel = QtWidgets.QLabel(self.layoutWidget_2)
        self.iconLabel.setMinimumSize(QtCore.QSize(22, 22))
        self.iconLabel.setMaximumSize(QtCore.QSize(22, 22))
        self.iconLabel.setObjectName("iconLabel")
        self.horizontalLayout_2.addWidget(self.iconLabel)
        self.msgLabel = QtWidgets.QLabel(self.layoutWidget_2)
        self.msgLabel.setObjectName("msgLabel")
        self.horizontalLayout_2.addWidget(self.msgLabel)
        self.closeBtnLabel = QClickLabel(self.centralWidget)
        self.closeBtnLabel.setGeometry(QtCore.QRect(370, 20, 10, 10))
        self.closeBtnLabel.setMaximumSize(QtCore.QSize(10, 10))
        self.closeBtnLabel.setObjectName("closeBtnLabel")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.okBtn.setText(_translate("Dialog", "确认"))
        self.cancelBtn.setText(_translate("Dialog", "取消"))
        self.titleLabel.setText(_translate("Dialog", "提示"))
        self.iconLabel.setText(_translate("Dialog", "icon"))
        self.msgLabel.setText(_translate("Dialog", "message"))
        self.closeBtnLabel.setText(_translate("Dialog", "x"))
