# Form implementation generated from reading ui file 'ui_msgbox.ui'
#
# Created by: PyQt5 UI code generator 6.1.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from modules.interaction.widget import QClickLabel


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(413, 193)
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.centralWidget = QtWidgets.QWidget(Dialog)
        self.centralWidget.setObjectName("centralWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralWidget)
        self.gridLayout.setObjectName("gridLayout")
        self.titleLabel = QtWidgets.QLabel(self.centralWidget)
        self.titleLabel.setStyleSheet("color: #2E3033; font-weight: 400; font-size: 16px;")
        self.titleLabel.setObjectName("titleLabel")
        self.gridLayout.addWidget(self.titleLabel, 0, 0, 1, 1)
        self.frame = QtWidgets.QFrame(self.centralWidget)
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout.addWidget(self.frame, 0, 1, 1, 1)
        self.frame_2 = QtWidgets.QFrame(self.centralWidget)
        self.frame_2.setMinimumSize(QtCore.QSize(138, 35))
        self.frame_2.setMaximumSize(QtCore.QSize(138, 16777215))
        self.frame_2.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_2.setObjectName("frame_2")
        self.gridLayout.addWidget(self.frame_2, 0, 2, 1, 1)
        self.closeBtnLabel = QClickLabel(self.centralWidget)
        self.closeBtnLabel.setMaximumSize(QtCore.QSize(10, 10))
        self.closeBtnLabel.setObjectName("closeBtnLabel")
        self.gridLayout.addWidget(self.closeBtnLabel, 0, 3, 1, 1)
        self.msgHLayout = QtWidgets.QHBoxLayout()
        self.msgHLayout.setSpacing(16)
        self.msgHLayout.setObjectName("msgHLayout")
        self.label = QtWidgets.QLabel(self.centralWidget)
        self.label.setMaximumSize(QtCore.QSize(10, 16777215))
        self.label.setText("")
        self.label.setObjectName("label")
        self.msgHLayout.addWidget(self.label)
        self.iconLabel = QtWidgets.QLabel(self.centralWidget)
        self.iconLabel.setMinimumSize(QtCore.QSize(22, 22))
        self.iconLabel.setMaximumSize(QtCore.QSize(22, 22))
        self.iconLabel.setObjectName("iconLabel")
        self.msgHLayout.addWidget(self.iconLabel)
        self.msgLabel = QtWidgets.QLabel(self.centralWidget)
        self.msgLabel.setMinimumSize(QtCore.QSize(0, 60))
        self.msgLabel.setMaximumSize(QtCore.QSize(16777215, 60))
        self.msgLabel.setObjectName("msgLabel")
        self.msgHLayout.addWidget(self.msgLabel)
        self.label_2 = QtWidgets.QLabel(self.centralWidget)
        self.label_2.setMaximumSize(QtCore.QSize(20, 16777215))
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.msgHLayout.addWidget(self.label_2)
        self.gridLayout.addLayout(self.msgHLayout, 1, 0, 1, 4)
        self.btnHlLayout = QtWidgets.QHBoxLayout()
        self.btnHlLayout.setObjectName("btnHlLayout")
        self.okBtn = QtWidgets.QPushButton(self.centralWidget)
        self.okBtn.setMinimumSize(QtCore.QSize(60, 30))
        self.okBtn.setMaximumSize(QtCore.QSize(60, 30))
        self.okBtn.setObjectName("okBtn")
        self.btnHlLayout.addWidget(self.okBtn)
        self.cancelBtn = QtWidgets.QPushButton(self.centralWidget)
        self.cancelBtn.setMinimumSize(QtCore.QSize(60, 30))
        self.cancelBtn.setMaximumSize(QtCore.QSize(60, 30))
        self.cancelBtn.setObjectName("cancelBtn")
        self.btnHlLayout.addWidget(self.cancelBtn)
        self.gridLayout.addLayout(self.btnHlLayout, 2, 2, 1, 2)
        self.verticalLayout.addWidget(self.centralWidget)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.titleLabel.setText(_translate("Dialog", "提示"))
        self.closeBtnLabel.setText(_translate("Dialog", "x"))
        self.iconLabel.setText(_translate("Dialog", "icon"))
        self.msgLabel.setText(_translate("Dialog", "message"))
        self.okBtn.setText(_translate("Dialog", "确认"))
        self.cancelBtn.setText(_translate("Dialog", "取消"))
